global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-servers'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['sw_team4_spring_stable:8080', 'sw_team4_spring_canary:8080']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['sw_team4_cadvisor:8080']
