upstream backend {
    server sw_team4_spring_stable:8080 weight=1;
    server sw_team4_spring_canary:8080 weight=1;
}

server {
    listen 80;

    location / {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
